# Generated by Django 4.2.5 on 2023-10-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
    ]
