# Generated by Django 4.2.5 on 2023-10-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_rename_tests_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='acurracy',
            new_name='accuracy',
        ),
    ]
