# Generated by Django 4.2.5 on 2023-10-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_rename_acurracy_test_accuracy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='text_types',
            new_name='test_type',
        ),
    ]
