# Generated by Django 4.2.5 on 2023-10-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_rename_text_types_test_test_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Test_Time',
        ),
    ]
