# Generated by Django 4.2.5 on 2023-10-08 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0005_rename_test_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_time',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Test_Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.PositiveIntegerField()),
                ('speed', models.PositiveIntegerField()),
                ('accuracy', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('raw_speed', models.PositiveIntegerField()),
                ('character', models.CharField(max_length=17)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
