# Generated by Django 4.2.5 on 2023-10-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0007_test_time_game_type_test_word_game_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_time',
            name='time_frame',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
